name: elementary_weather_flutter
description: Example flutter project with using elementary package.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.1
  elementary: ^2.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^0.23.0+1
  get_it: ^7.2.0
  golden_toolkit: ^0.12.0
  intl: ^0.17.0
  json_annotation: ^4.1.0

dev_dependencies:
  build_runner: ^2.1.5
  dart_code_metrics: ^5.7.3
  elementary_test: ^1.1.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: 6.4.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/weather/
    - assets/icon/

  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Bold.ttf
        - asset: fonts/Gilroy-Medium.ttf
        - asset: fonts/Gilroy-Regular.ttf
